[package]
name = "thin-slice"
description = "Thin immutable zero-copy slice type"
version = "0.0.1"
edition = "2021"
rust-version = "1.70"
readme = "README.md"
include = ["src/**/*", "LICENSE-APACHE", "LICENSE-MIT", "README.md"]

[lib]

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
nanoid = "0.4.0"
rand = "0.8.5"

[[bench]]
name = "bench"
harness = false
